## Copyright (c) 2023 Salesforce.com, inc.
## All rights reserved.
## SPDX-License-Identifier: BSD-3-Clause
## For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
##
##
workflow_config:  
  output_dir: "/Users/mohit.gurnani/projects/reports/mldata3"
  output_file_type: "csv"
  training_type: "unsupervised"
  deduplicate_test: True
  test_data_frac_pos: 0.5
  dataset_name: normal
  train_test_shuffle: True

  data_loader_config:
    train: "/Users/mohit.gurnani/Downloads/acropolis_crash_latest.csv"
    test: "/Users/mohit.gurnani/Downloads/ahv_management.csv"

  open_set_partitioner_config:
    session_window: True
    sliding_window: -1
    logsequence_delim: "[SEP]"
    group_by_time: "4S"

  log_vectorizer_config:
    algo_name: "logbert"
    algo_param:
      model_name: "bert-base-cased"
      max_token_len: 512
      custom_tokens: ["BLOCK", "IP", "HEX", "INT"]
      output_dir: "/Users/mohit.gurnani/projects/reports/mldata3"
      tokenizer_dirname: "logbert_tokenizer"
      dataset: "normal"


  nn_anomaly_detection_config:
      algo_name: "logbert"
      algo_params:
          pretrain_from_scratch: False
          model_name: "bert-base-cased"
          learning_rate: 0.01
          num_train_epochs: 3
          max_token_len: 256
          per_device_train_batch_size: 16
          per_device_eval_batch_size: 32
          weight_decay: 0.01
          logging_steps: 50,
          evaluation_strategy: "steps"
          save_steps: 50
            #          resume_from_checkpoint: "/home/ml/data/temp_output_n1/models/bert-base-cased/checkpoint-1000"
          save_strategy: "steps"
          save_total_limit: 3
          mask_ngram: 8
          eval_steps: 50
          tokenizer_dirpath: "/Users/mohit.gurnani/projects/reports/mldata3/bert-base-cased_tokenizer"
          output_dir: "/Users/mohit.gurnani/projects/reports/mldata3/models"
          multi_classifier: True
